{{- if not .Values.neo4j.persistentVolumeClaimName -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dependencies-graph.fullname" . }}-volume-claim
  labels:
    type: longhorn
    app: {{ include "dependencies-graph.fullname" . }}
    {{- include "dependencies-graph.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}