name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: helm lint
        working-directory: dependencies-graph

      - name: Try install
        run: helm install dependencies-graph ./dependencies-graph --set fullnameOverride=graph --namespace dependencies-graph --dry-run --debug
    
